language: java
jdk:
  - openjdk11
script:
  - mvn clean install
cache:
  directories:
    - $HOME/.m2
services:
  - postgresql
before_script:
      - psql -c 'create database contacts;' -U postgres
before_install:
  - chmod +x mvnw
