version: '3'

services:
#  postgres:
#    image: 'library/postgres:13.2'
#    network_mode: bridge
#    container_name: postgres
#    volumes:
#      - ./db:/docker-entrypoint-initdb.d/
#    expose:
#      - 5432
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=db
#    restart: unless-stopped

  application:
    image:  application:latest
#    network_mode: bridge
    container_name: application
    expose:
      - 8080
    ports:
      - 8080:8080
#    depends_on:
#      - postgres
#    links:
#      - postgres
